### PR TITLE
fix: swap initiative bugs

### LINKED ISSUE #58: Swap initiative menu item is not visible if the game starts without combatants in the combat tracker
### Describe the bug

v13 context menu is created on startup, not every time it is displayed. The condition for menuitems uses the state of combat.combatants as it is during startup, not the state when the condition is evaluated.

### Reproduction

Start game without combatants
Add two combatants
Right click combatant --> Missing "Swap Initiative" menu item
Press F5
Right click combatant --> "Swap Initiative" menu item exists

### System Info

```sh
Foundry v13.345
```

### Logs

_No response_

### Priority this issue should have?

High (a broken feature, major functional impact)

### Validations

- [x] Done a clean install of the system.
- [x] Disabled all modules.
- [x] Checked if the issue is present in a new world instance (create a new world in foundry using the module).

### PR DESCRIPTION
**Pull request by pafvel**
## Summary

Fixes #58 and #59

### PR Type

- [ ] This PR is a code change that implements a feature request.
- [ ] This PR adds a new feature that is not an open feature request.
- [x] This PR fixes an issue.
- [ ] This PR is not a code change (e.g. documentation, README, ...)

### Other
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] If code changes were made then they have been tested.
- [ ] I have updated the documentation to reflect the changes.

### CODE REVIEW

File: src/sidebar/combat-tracker.js [hunk 1]
```diff
@@ -112,16 +112,6 @@ export default class YearZeroCombatTracker extends foundry.applications.sidebar.
...
-    // The combat tracker will initialize context menus regardless of there being a combat active
-    if (!game.combat) return contextMenu;
-
-    // Scoped Constants
-    /** @type {YearZeroCombat} */
-    const combat = game.combat;
-
-    /** @type {Collection.<YearZeroCombatant>} EmbeddedCollection */
-    const combatants = combat.combatants;
-
```
Comment (Stefouch) [inline src/sidebar/combat-tracker.js:124]: Why removing the scoped constants? The type definition for `YearZeroComnbat` and `YearZeroCombatant` helps the VS Code's intellisense to retrieve our custom methods added to these classes.

File: src/combat/combatant.js [hunk 2]
```diff
@@ -298,15 +298,15 @@ export default class YearZeroCombatant extends Combatant {
       const thisActions = this.#getSingleActionStatus(this);
       const combatantActions = this.#getSingleActionStatus(tCombatant);
 
-      const result = await this.combat.updateEmbeddedDocuments('Combatant', updates, { turnEvents: false });
```
Comment (Stefouch) [inline src/combat/combatant.js:301]: Are we sure we can remove `turnEvents: false`. I can't remember what it was doing and can't find the API documentation about it.

Comment (pafvel) [reply src/combat/combatant.js:301]: Yes see https://github.com/foundryvtt/foundryvtt/issues/12990

File: src/sidebar/combat-tracker.js (hunk 1 above)
Comment (Stefouch) [reply src/sidebar/combat-tracker.js:124]: Ok I understand the importance to remove lines 115-116.

But why removing lines 118-123 ?

File: src/combat/combatant.js (hunk 2 above)
Comment (Stefouch) [reply src/combat/combatant.js:301]: Oh very interesting reading! Thank you!

**Review by Stefouch — APPROVED** [review]
